on:
  pull_request_review:
    types: [submitted]

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Create a comment
        uses: asadreev/comment-on-task-github-action@v1.3
        id: createComment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
          comment-text: "' {{PR_ID}} {{PR_NAME}}' was {{PR_STATE}} ({{PR_URL}})"
          blocked-projects: |
            1117470676484494
      - name: Get status
        run: echo "Status is ${{ steps.createComment.outputs.status }}"
